projekt/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace projekt.Models
{
    public class Comment
    {
        public int CommentID { get; set; }

        public WebAppUser Author { get; set; }
        public Recipe Recipe { get; set; }
        public string Body { get; set; }
    }
}
    

projekt/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace projekt.Models
{
    public class Recipe
    {
        public int RecipeID { get; set; }

        [Required]
        public string Name { get; set; }

        public WebAppUser Author { get; set; }
        [Required]
        public Category Category { get; set; }
        [Required]
        public DifficultyLevel DifficultyLevel { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public ICollection<FavoriteRecipe> FavoriteRecipes { get; set; }
        [Required]
        public string Tags { get; set; }
        public ICollection<Tagging> Taggings { get; set; }

        public string Description { get; set; }
        [Required]
        public ICollection<Step> Steps { get; set; }
        [Required]
        public ICollection<Ingredient> Ingredients { get; set; }
    }
}

projekt/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using projekt.Models;
using projekt.Data;
using Microsoft.EntityFrameworkCore;

namespace projekt.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private UserManager<WebAppUser> _userManager;
        private IUserValidator<WebAppUser> _userValidator;
        private IPasswordValidator<WebAppUser> _passwordValidator;
        private IPasswordHasher<WebAppUser> _passwordHasher;
        private readonly AppDbContext _context;

        public AdministrationController(UserManager<WebAppUser> umn, IUserValidator<WebAppUser> uvl, 
            IPasswordValidator<WebAppUser> pvl, IPasswordHasher<WebAppUser> psh, AppDbContext ctx)
        {
            _userManager = umn;
            _userValidator = uvl;
            _passwordValidator = pvl;
            _passwordHasher = psh;
            _context = ctx;
        }

        public ViewResult Index()
        {
            return View();
        }

        public async Task<ViewResult> Users()
        {
            return View(await _userManager.Users.ToListAsync());
        }

        public async Task<ViewResult> Recipes()
        {
            return View(await _context.Recipes
                .Include(x => x.Author)
                .Include(x => x.Category)
                .Include(x => x.DifficultyLevel)
                .ToListAsync());
        }

        public async Task<ViewResult> Comments()
        {
            return View(await _context.Comments
                .Include(x => x.Author)
                .Include(x => x.Recipe)
                .ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            //WebAppUser user = await _userManager.FindByIdAsync(id);
            WebAppUser user = await _context.Users
                .Include(r => r.Recipes)
                    .ThenInclude(a => a.Author)
                .Include(c => c.Comments)
                    .ThenInclude(a => a.Author)
                .Include(f => f.FavoriteRecipes)
                .FirstOrDefaultAsync(x => x.Id == id);

            foreach (Recipe recipe in user.Recipes)
            {
                recipe.Author = null;
            }
            foreach (Comment comment in user.Comments)
            {
                comment.Author = null;
            }
            foreach (FavoriteRecipe favoriteRecipe in user.FavoriteRecipes)
            {
                _context.FavoriteRecipes.Remove(favoriteRecipe);
            }

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Users");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Brak takiego użytkownika");
            }
            return View("Users");
        }

        public async Task<IActionResult> EditUser(string id)
        {
            WebAppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("Users");
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string id, string email, string password)
        {
            WebAppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                IdentityResult validEmail = await _userValidator.ValidateAsync(_userManager, user);
                if (!validEmail.Succeeded)
                {
                    foreach (IdentityError error in validEmail.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                else
                {
                    user.UserName = user.Email;
                }

                IdentityResult validPassword = null;
                bool emptyPassword = string.IsNullOrEmpty(password);
                if (!emptyPassword)
                    {
                    validPassword = await _passwordValidator.ValidateAsync(_userManager, user, password);
                    if (!validPassword.Succeeded)
                    {
                        foreach (IdentityError error in validPassword.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                    else
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, password);
                    }
                }
                if ((validEmail.Succeeded && emptyPassword) ||
                    (validEmail.Succeeded && validPassword.Succeeded && !emptyPassword))
                    {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Users");
                    }
                    else
                    {
                        foreach (IdentityError error in validPassword.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                return View(user);
            }
            else
            {
                ModelState.AddModelError("", "Nie znaleziono użytkownika");
            }
            return View(user);
        }


        [HttpPost]
        public IActionResult DeleteRecipe(int id)
        {
            Recipe recipe = _context.Recipes
                .Include(r => r.Comments)
                .Include(r => r.Taggings)
                .Include(r => r.Ingredients)
                .Include(r => r.Steps)
                .FirstOrDefault(p => p.RecipeID == id);

            foreach (Comment comment in recipe.Comments)
            {
                _context.Comments.Remove(comment);
            }

            foreach (Tagging tagging in recipe.Taggings)
            {
                _context.Taggings.Remove(tagging);
            }

            foreach (Ingredient ingredient in recipe.Ingredients)
            {
                _context.Ingredients.Remove(ingredient);
            }

            foreach (Step step in recipe.Steps)
            {
                _context.Steps.Remove(step);
            }

            if (recipe != null)
            {
                _context.Recipes.Remove(recipe);
                _context.SaveChanges();
            }

            return RedirectToAction("Recipes");
        }
    }
}

projekt/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;
using projekt.Models.ViewModels;

namespace projekt.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext ctx)
        {
            _context = ctx;
        }

        public async Task<IActionResult> Index()
        {
            var categories = from c in _context.Categories select c;

            return View(await categories.ToListAsync());
        }

        public async Task<IActionResult> AllRecipes(int id)
        {
            Category category = await _context.Categories
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.CategoryID == id);

            List<Recipe> recipes = _context.Recipes.Where(r => r.Category.CategoryID == id).ToList();

            IndexVM IndexVM = new IndexVM
            {
                Recipes = recipes,
                Category = category
            };

            return View(IndexVM);
        }
    }
}

projekt/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;
using projekt.Models.ViewModels;

namespace projekt.Controllers
{
    public class CommentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<WebAppUser> _userManager;
        private readonly SignInManager<WebAppUser> _signInManager;

        public CommentController(AppDbContext ctx, IRecipeRepository rec, UserManager<WebAppUser> umn, SignInManager<WebAppUser> sim)
        {
            _context = ctx;
            _userManager = umn;
            _signInManager = sim;
        }

        [HttpPost]
        public async Task<IActionResult> Add(NewCommentVM newComment)
        {
            if (ModelState.IsValid)
            {
                Comment comment = new Comment()
                {
                    Author = await _userManager.GetUserAsync(HttpContext.User),
                    Recipe = await _context.Recipes.Where(x => x.RecipeID == newComment.Recipe).SingleAsync(),
                    Body = newComment.Body
                };
                _context.Comments.Add(comment);
                _context.SaveChanges();
            }

            return RedirectToAction("Details", "Recipe", new { id = newComment.Recipe});
        }

        public async Task<IActionResult> Edit(int id)
        {
            Comment comment = await _context.Comments
                .Include(x => x.Author)
                .FirstOrDefaultAsync(p => p.CommentID == id);

            if (comment != null)
            {
                EditCommentVM commentToEdit = new EditCommentVM()
                {
                    Body = comment.Body,
                    Author = comment.Author?.Email,
                    OriginalComment = comment.CommentID
                };

                return View(commentToEdit);
            }

            return RedirectToAction("Comments");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCommentVM comment)
        {
            if (ModelState.IsValid)
            {
                Comment originalComment = await _context.Comments.FirstOrDefaultAsync(p => p.CommentID == comment.OriginalComment);
                if (originalComment != null)
                {
                    originalComment.Body = comment.Body;
                    _context.SaveChanges();
                    return RedirectToAction("Comments", "Administration");
                }
            }

            return View(comment);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            Comment comment = await _context.Comments.FirstOrDefaultAsync(p => p.CommentID == id);
            if (comment != null)
            {
                _context.Comments.Remove(comment);
                _context.SaveChanges();
            }
            return RedirectToAction("Comments", "Administration");
        }
    }
}

projekt/Views/Administration/Comments.cshtml
@model IEnumerable<Comment>

@{
    ViewData["Title"] = "Komentarze";
}

<h2>Lista komentarzy</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Autor</th>
        <th>Przepis</th>
        <th>Treść</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3">Brak komentarzy</td></tr>
    }
    else
    {
        foreach (Comment comment in Model)
        {
            <tr>
                <td>@comment.CommentID</td>
                @if  (comment.Author == null)
                {
                    <td><i>profil skasowany</i></td>
                }
                else
                {
                    <td><a asp-controller="Account" asp-action="Details" asp-route-id="@comment.Author.Id">@comment.Author</a></td>
                }
                <td><a asp-controller="Recipe" asp-action="Details" asp-route-id="@comment.Recipe.RecipeID">@comment.Recipe.Name</a></td>
                <td>@comment.Body</td>

                <td>
                    <form asp-controller="Comment" asp-action="Delete" asp-route-id="@comment.CommentID" method="post">
                        <a asp-controller="Comment" asp-action="Edit" class="btn btn-success" asp-route-id="@comment.CommentID">Edytuj</a>
                        <button type="submit" class="btn btn-danger">Usuń</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>

projekt/Views/Administration/CreateUser.cshtml
@model CreateUserModel

@{
    ViewData["Title"] = "Tworzenie użytkownika";
}

<h2>Utwórz użytkownika</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="CreateUser" method="post">
    <div class="form-group">
        <label asp-for="Email">Adres email</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password">Hasło</label>
        <input asp-for="Password" class="form-control" type="password" />
    </div>
    <button type="submit" class="btn btn-success">Utwórz</button>
    <a asp-action="Users" class="btn btn-danger">Anuluj</a>
</form>

projekt/Views/Administration/EditUser.cshtml
@model WebAppUser

@{
    ViewData["Title"] = "Edycja użytkownika";
}

<h2>Edytuj użytkownika @Model.Id</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="EditUser" method="post">
    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Hasło:</label>
        <input name="password" class="form-control" type="password">
    </div>

    <button class="btn btn-success">Zapisz zmiany</button>
    <a class="btn btn-danger" asp-action="Users">Anuluj</a>
</form>

projekt/Views/Administration/Index.cshtml
@{
    ViewData["Title"] = "Administracja";
}

<br />
<div>
    <a class="btn btn-info" asp-action="Users">Zarządzaj użytkownikami</a>
    <a class="btn btn-info" asp-action="Recipes">Zarządzaj przepisami</a>
    <a class="btn btn-info" asp-action="Comments">Zarządzaj komentarzami</a>
</div>

projekt/Views/Administration/Recipes.cshtml
@model IEnumerable<Recipe>

@{
    ViewData["Title"] = "Przepisy";
}

<br />
<div>
    <a class="btn btn-primary" asp-controller="Recipe" asp-action="Add">Dodaj przepis</a>
</div>

<h2>Lista przepisów</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Nazwa</th>
        <th>Autor</th>
        <th>Kategoria</th>
        <th>Poziom trudności</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3">Brak przepisów</td></tr>
    }
    else
    {
        foreach (Recipe recipe in Model)
        {
            <tr>
                <td>@recipe.RecipeID</td>
                <td>@recipe.Name</td>
                @if (recipe.Author == null)
                {
                    <td><p><i>profil skasowany</i></p></td>
                }
                else
                {
                    <td><a asp-controller="Account" asp-action="Details" asp-route-id="@recipe.Author.Id">@recipe.Author</a></td>
                }
                
                <td><a asp-controller="Category" asp-action="AllRecipes" asp-route-id="@recipe.Category.CategoryID">@recipe.Category.Name</a></td>
                <td>@recipe.DifficultyLevel.Name</td>

                <td>
                    <form asp-action="DeleteRecipe" asp-route-id="@recipe.RecipeID" method="post">
                        <a class="btn btn-info" asp-controller="Recipe" asp-action="Details" asp-route-id="@recipe.RecipeID">Szczegóły</a>
                        <a class="btn btn-success" asp-controller="Recipe" asp-action="Edit" asp-route-id="@recipe.RecipeID">Edytuj</a>
                        <button type="submit" class="btn btn-danger">Usuń</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>

projekt/Views/Administration/Users.cshtml
@model IEnumerable<WebAppUser>

@{
    ViewData["Title"] = "Użytkownicy";
}

<br />
<div>
    <a class="btn btn-primary" asp-controller="Account" asp-action="Register">Stwórz nowe konto</a>
</div>

<h2>Lista użytkowników</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Nazwa</th>
        <th>Email</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3">Brak zarejestrowanych użytkowników</td></tr>
    }
    else
    {
        foreach(WebAppUser user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                        <a class="btn btn-info" asp-action="Details" asp-controller="Account" asp-route-id="@user.Id">Profil</a>
                        <a class="btn btn-success" asp-action="EditUser" asp-route-id="@user.Id">Edytuj</a>
                        <button type="submit" class="btn btn-danger">Usuń</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>

projekt/Views/Administration/UsersList.cshtml
@model IEnumerable<WebAppUser>

@{
    ViewData["Title"] = "Użytkownicy";
}

<br />
<div>
    <a class="btn btn-primary" asp-action="CreateUser">Stwórz nowe konto</a>
</div>

<h2>Lista użytkowników</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr><td colspan="3">Brak zarejestrowanych użytkowników</td></tr>
    }
    else
    {
        foreach(WebAppUser user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>
                    <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                        <a class="btn btn-success" asp-action="EditUser" asp-route-id="@user.Id">Edytuj</a>
                        <button type="submit" class="btn btn-danger">Usuń</button>
                    </form>
                </td>
            </tr>
        }
    }
</table>