projekt/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace projekt.Models
{
    public class Recipe
    {
        public int RecipeID { get; set; }

        [Required]
        public string Name { get; set; }

        public WebAppUser Author { get; set; }
        [Required]
        public Category Category { get; set; }
        [Required]
        public DifficultyLevel DifficultyLevel { get; set; }
        public ICollection<Comment> Comments { get; set; }
        public ICollection<FavoriteRecipe> FavoriteRecipes { get; set; }
        [Required]
        public string Tags { get; set; }
        public ICollection<Tagging> Taggings { get; set; }

        public string Description { get; set; }
        [Required]
        public ICollection<Step> Steps { get; set; }
        [Required]
        public ICollection<Ingredient> Ingredients { get; set; }
    }
}

projekt/Components/AddCommentViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using projekt.Models;
using projekt.Models.ViewModels;

namespace projekt.Components
{
    public class AddCommentViewComponent : ViewComponent
    {
        private readonly SignInManager<WebAppUser> _signInManager;
        private readonly UserManager<WebAppUser> _userManager;

        public AddCommentViewComponent(SignInManager<WebAppUser> sim, UserManager<WebAppUser> umn)
        {
            _signInManager = sim;
            _userManager = umn;
        }

        public async Task<IViewComponentResult> InvokeAsync(int recipeID)
        {
            if (_signInManager.IsSignedIn(HttpContext.User))
            {
                WebAppUser user = await _userManager.GetUserAsync(HttpContext.User);
                NewCommentVM newComment = new NewCommentVM()
                {
                    Author = user.Id,
                    Recipe = recipeID
                };

                return View("Logged", newComment);
            }
            else
            {
                return View();
            }
        }
    }
}

projekt/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using projekt.Models;
using projekt.Data;
using Microsoft.EntityFrameworkCore;

namespace projekt.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : Controller
    {
        private UserManager<WebAppUser> _userManager;
        private IUserValidator<WebAppUser> _userValidator;
        private IPasswordValidator<WebAppUser> _passwordValidator;
        private IPasswordHasher<WebAppUser> _passwordHasher;
        private readonly AppDbContext _context;

        public AdministrationController(UserManager<WebAppUser> umn, IUserValidator<WebAppUser> uvl, 
            IPasswordValidator<WebAppUser> pvl, IPasswordHasher<WebAppUser> psh, AppDbContext ctx)
        {
            _userManager = umn;
            _userValidator = uvl;
            _passwordValidator = pvl;
            _passwordHasher = psh;
            _context = ctx;
        }

        public ViewResult Index()
        {
            return View();
        }

        public async Task<ViewResult> Users()
        {
            return View(await _userManager.Users.ToListAsync());
        }

        public async Task<ViewResult> Recipes()
        {
            return View(await _context.Recipes
                .Include(x => x.Author)
                .Include(x => x.Category)
                .Include(x => x.DifficultyLevel)
                .ToListAsync());
        }

        public async Task<ViewResult> Comments()
        {
            return View(await _context.Comments
                .Include(x => x.Author)
                .Include(x => x.Recipe)
                .ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            //WebAppUser user = await _userManager.FindByIdAsync(id);
            WebAppUser user = await _context.Users
                .Include(r => r.Recipes)
                    .ThenInclude(a => a.Author)
                .Include(c => c.Comments)
                    .ThenInclude(a => a.Author)
                .Include(f => f.FavoriteRecipes)
                .FirstOrDefaultAsync(x => x.Id == id);

            foreach (Recipe recipe in user.Recipes)
            {
                recipe.Author = null;
            }
            foreach (Comment comment in user.Comments)
            {
                comment.Author = null;
            }
            foreach (FavoriteRecipe favoriteRecipe in user.FavoriteRecipes)
            {
                _context.FavoriteRecipes.Remove(favoriteRecipe);
            }

            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Users");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Brak takiego użytkownika");
            }
            return View("Users");
        }

        public async Task<IActionResult> EditUser(string id)
        {
            WebAppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }

            return RedirectToAction("Users");
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(string id, string email, string password)
        {
            WebAppUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                IdentityResult validEmail = await _userValidator.ValidateAsync(_userManager, user);
                if (!validEmail.Succeeded)
                {
                    foreach (IdentityError error in validEmail.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
                else
                {
                    user.UserName = user.Email;
                }

                IdentityResult validPassword = null;
                bool emptyPassword = string.IsNullOrEmpty(password);
                if (!emptyPassword)
                    {
                    validPassword = await _passwordValidator.ValidateAsync(_userManager, user, password);
                    if (!validPassword.Succeeded)
                    {
                        foreach (IdentityError error in validPassword.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                    else
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, password);
                    }
                }
                if ((validEmail.Succeeded && emptyPassword) ||
                    (validEmail.Succeeded && validPassword.Succeeded && !emptyPassword))
                    {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Users");
                    }
                    else
                    {
                        foreach (IdentityError error in validPassword.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
                return View(user);
            }
            else
            {
                ModelState.AddModelError("", "Nie znaleziono użytkownika");
            }
            return View(user);
        }


        [HttpPost]
        public IActionResult DeleteRecipe(int id)
        {
            Recipe recipe = _context.Recipes
                .Include(r => r.Comments)
                .Include(r => r.Taggings)
                .Include(r => r.Ingredients)
                .Include(r => r.Steps)
                .FirstOrDefault(p => p.RecipeID == id);

            foreach (Comment comment in recipe.Comments)
            {
                _context.Comments.Remove(comment);
            }

            foreach (Tagging tagging in recipe.Taggings)
            {
                _context.Taggings.Remove(tagging);
            }

            foreach (Ingredient ingredient in recipe.Ingredients)
            {
                _context.Ingredients.Remove(ingredient);
            }

            foreach (Step step in recipe.Steps)
            {
                _context.Steps.Remove(step);
            }

            if (recipe != null)
            {
                _context.Recipes.Remove(recipe);
                _context.SaveChanges();
            }

            return RedirectToAction("Recipes");
        }
    }
}

projekt/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using projekt.Data;
using projekt.Models;
using projekt.Models.ViewModels;

namespace projekt.Controllers
{
    public class TagController : Controller
    {
        private readonly AppDbContext _context;

        public TagController(AppDbContext ctx)
        {
            _context = ctx;
        }

        public async Task<IActionResult> Index(string id)
        {
            Tag tag = await _context.Tags
                .Include(t => t.Taggings)
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.Name == id);

            TagVM tagVM = new TagVM();

            if (tag != null)
            {
                List<Recipe> taggedRecipes = new List<Recipe>();
                foreach (var recipe in tag.Taggings)
                {
                    taggedRecipes.Add(await _context.Recipes.Include(x => x.Category).FirstOrDefaultAsync(x => x.RecipeID == recipe.RecipeID));
                }
                tagVM.TagName = tag.Name;
                tagVM.Recipes = taggedRecipes;
            }
            else
            {
                tagVM.TagName = id;
                tagVM.Recipes = new List<Recipe>();
            } 
            return View(tagVM);
        }
    }
}

projekt/Views/Recipe/Add.cshtml
@model NewRecipeVM

@{
    ViewData["Title"] = "Dodawanie przepisu";
}

<h2>Dodaj przepis</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Category" class="control-label">Kategoria</label>
        <select asp-for="Category" class="form-control" asp-items="ViewBag.Categories"></select>
    </div>
    <div class="form-group">
        <label asp-for="Name">Nazwa</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description">Opis przepisu</label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>

    <div class="form-group" id="ingredient-list">
        <label asp-for="Ingredients">Lista składników</label>
        <input asp-for="Ingredients[0].Name" class="ingredients form-control" />
    </div>
    <a href="#" id="add-ingredient" class="btn btn-info">Dodaj kolejny składnik</a>

    <div class="form-group" id="step-list">
        <label asp-for="Steps">Instrukcja wykonania</label>
        <input asp-for="Steps[0].Description" class="steps form-control" />
    </div>
    <a href="#" id="add-step" class="btn btn-info">Dodaj kolejny krok</a>

    <div class="form-group">
        <label asp-for="DifficultyLevel" class="control-label">Poziom trudności wykonania:</label>
        <select asp-for="DifficultyLevel" class="form-control" asp-items="ViewBag.DifficultyLevels"></select>
    </div>
    <div class="form-group">
        <label asp-for="Tags">Tagi (oddzielone spacją): </label>
        <input asp-for="Tags" class="form-control">
    </div>

    <button type="submit" class="btn btn-success">Dodaj</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Anuluj</a>
</form>

@section Scripts  {
    <script type="text/javascript">
        $(function () {
            $("#add-ingredient").click(function (f) {
                f.preventDefault();
                var j = $(".ingredients").length;
                var m = '<input class="ingredients form-control" type="text" name="Ingredients[' + j + '].Name" />';
                $("#ingredient-list").append(m);
            });
        });

        $(function () {
            $("#add-step").click(function (e) {
                e.preventDefault();
                var i = $(".steps").length;
                var n = '<input class="steps form-control" type="text" name="Steps[' + i + '].Description" />';
                $("#step-list").append(n);
            });
        });
    </script>
}

projekt/Views/Recipe/AddRecipe.cshtml
@model NewRecipeVM

@{
    ViewData["Title"] = "Dodawanie przepisu";
}

<h2>Dodaj przepis</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="AddRecipe" method="post">
    <div class="form-group">
        <label asp-for="DifficultyLevel" class="control-label">Poziom trudności wykonania:</label>
        <select asp-for="DifficultyLevel" class="form-control" asp-items="ViewBag.DifficultyLevels"></select>
    </div>
    <div class="form-group">
        <label asp-for="Name">Nazwa</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Body">Opis</label>
        <textarea asp-for="Body" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="Category" class="control-label">Kategoria</label>
        <select asp-for="Category" class="form-control" asp-items="ViewBag.Categories"></select>
    </div>

    <button type="submit" class="btn btn-success">Dodaj</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Anuluj</a>
</form>

projekt/Views/Recipe/Details.cshtml
@model RecipeDetailsVM

@{
    ViewData["Title"] = @Model.Recipe.Name;
}

<div class="col-md-9">
    <div>
        <h2>@Model.Recipe.Name</h2>

        @await Component.InvokeAsync("FavoriteRecipes",
         new { recipeID = Model.Recipe.RecipeID, favoriteRecipeID = Model.FavoriteRecipeID, isAuthor = Model.IsAuthor })

        @if (Model.Recipe.Author == null)
        {
            <p>autor: <i>profil skasowany</i></p>
        }
        else
        {
            <p>autor: <a asp-controller="Account" asp-action="Details" asp-route-id="@Model.Recipe.Author.Id">@Model.Recipe.Author.Email</a></p>
        }

        <p>kategoria: <a asp-controller="Home" asp-action="Index" asp-route-id="@Model.Recipe.Category.CategoryID">@Model.Recipe.Category.Name</a></p>
        <p>stopień trudności: @Model.Recipe.DifficultyLevel.Name</p>
        <p style="background:#f5f5f0;padding:1%;margin:1%;border-radius:25px;">Opis przepisu: <br />@Model.Recipe.Description</p>
    </div>

    <div style="padding:1%;margin:1%;border-radius:25px;">
        <h4>Lista składników</h4>
        <ul>
            @foreach (var ingredient in Model.Recipe.Ingredients)
            {
                <li>@ingredient.Name</li>
            }
        </ul>
    </div>

    <div style="padding:1%;margin:1%;border-radius:25px;">
        <h4>Instrukcja wykonania</h4>
        <ol>
            @foreach (var step in Model.Recipe.Steps)
            {
                <li>@step.Description</li>
            }
        </ol>
    </div>

    <div>
        tagi:
        @foreach (var tag in Model.Recipe.Taggings)
        {
            <a asp-controller="Tag" asp-action="Index" class="btn btn-default" asp-route-id="@tag.TagName">@tag.TagName</a>
        }
    </div>

    <div>
        @await Component.InvokeAsync("AddComment", new { recipeID = Model.Recipe.RecipeID })

        <h3>Komentarze:</h3>
        @foreach (var c in Model.Recipe.Comments)
        {
            <div style="background:#f5f5f0;padding:1%;margin:1%">
                @if (c.Author == null)
                {
                    <h6><i>profil skasowany</i></h6>
                }
                else
                {
                    <h6><a asp-controller="Account" asp-action="Details" asp-route-id="@c.Author.Id">@c.Author</a></h6>
                }

                <p>@c.Body</p>
            </div>
        }
    </div>
</div>

<div class="col-md-3">
    @{string imgpath = Model.Recipe.RecipeID + ".jpg"; }
    <img style="margin-top:5%;width:100%;height:100%;" alt="zdjęcie gotowego dania" src="~/images/recipes/@imgpath" asp-append-version="true">
</div>

projekt/Views/Recipe/Edit.cshtml
@model EditRecipeVM

@{
    ViewData["Title"] = "Edycja przepisu";
}

<h2>Edytuj przepis</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="OriginalRecipe" value="@Model.OriginalRecipe" />
    <div class="form-group">
        <label asp-for="DifficultyLevel" class="control-label">Poziom trudności wykonania:</label>
        <select asp-for="DifficultyLevel" class="form-control" asp-items="ViewBag.DifficultyLevels"></select>
    </div>
    <div class="form-group">
        <label asp-for="Name">Nazwa:</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Description">Treść:</label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group" id="ingredient-list">
        <label asp-for="Ingredients">Lista składników</label>
        @for (int i = 0; i < Model.Ingredients.Count(); i++)
        {
            <input asp-for="Ingredients[i].Name" class="ingredients form-control" id="ingredient-@i" />
        }
    </div>
    <a href="#" id="add-ingredient" class="btn btn-info" onclick="addIngredient()">Dodaj kolejny składnik</a>

    <div class="form-group" id="step-list">
        <label asp-for="Steps">Instrukcja wykonania</label>
        @for (int i = 0; i < Model.Steps.Count(); i++)
        {
            <input asp-for="Steps[i].Description" class="steps form-control" id="step-@i" />
        }
    </div>
    <a href="#" id="add-step" class="btn btn-info">Dodaj kolejny krok</a>


    <div class="form-group">
        <label asp-for="Category" class="control-label">Kategoria</label>
        <select asp-for="Category" class="form-control" asp-items="ViewBag.Categories"></select>
    </div>
    <div class="form-group">
        <label asp-for="Tags" class="control-label">Tagi</label>
        <input asp-for="Tags" class="form-control">
    </div>

    <button class="btn btn-success">Zapisz zmiany</button>
    <a class="btn btn-danger" asp-controller="Administration" asp-action="Recipes">Anuluj</a>
</form>

@section Scripts  {
    <script type="text/javascript">
        $(function () {
            $("#add-ingredient").click(function (f) {
                f.preventDefault();
                var j = $(".ingredients").length;
                var m = '<input class="ingredients form-control" id="ingredient-' + j +'" type="text" name="Ingredients[' + j + '].Name" />';
                $("#ingredient-list").append(m);
            });
        });

        $(function () {
            $("#add-step").click(function (e) {
                e.preventDefault();
                var i = $(".steps").length;
                var n = '<input class="steps form-control" type="text" name="Steps[' + i + '].Description" />';
                $("#step-list").append(n);
            });
        });    
    </script>
}